website/auth.py
from flask import Blueprint, render_template, request, flash, redirect, url_for, abort
from .models import User
from werkzeug.security import generate_password_hash, check_password_hash
from . import db, create_app # =  from __init__.py import db
from flask_login import login_user, login_required, logout_user, current_user
from .models import Role, Source, Wood, Category
from werkzeug.utils import secure_filename
import os
import locale
import requests


auth_blueprint = Blueprint('auth_blueprint', __name__)

PROFILE_FOLDER = 'website/static/profiles'
STATIC_IMG_FOLDER = 'website/static/images'
ALLOWED_EXTENSIONS = {'png', 'jpg', 'jpeg'}

G_LEN_EMAIL = 4
G_LEN_FNAME = 2
G_LEN_LNAME = 2
G_LEN_UNAME = 4
G_LEN_PWORD = 7
NG_LEN_EMAIL = 50
NG_LEN_FNAME = 50
NG_LEN_LNAME = 50
NG_LEN_UNAME = 50
NG_LEN_PWORD = 50

# ตั้งค่า locale เป็น 'th_TH.UTF-8' เพื่อให้ Python รู้จักการเรียงลำดับภาษาไทย
locale.setlocale(locale.LC_COLLATE, 'th_TH.UTF-8')


def allowed_file(filename):
    return '.' in filename and filename.rsplit('.', 1)[1].lower() in ALLOWED_EXTENSIONS


# route

# @auth_blueprint.route('/sign-up', methods=['GET', 'POST'])
# def sign_up():

#     # กำหนด key ในการเรียงลำดับตามตัวอักษรภาษาไทย
#     sorted_roles = sorted(Role.query.all(), key=lambda x: locale.strxfrm(x.role_name))

#     if request.method == 'POST':
        
#         print(request.form)

#         secret_response = request.form['g-recaptcha-response']

#         verify_response = requests.post(url=f"{create_app().config['VERIFY_URL']}?secret={create_app().config['RECAPTCHA_SECRET_KEY']}&response={secret_response}").json()


#         if verify_response['success'] == False or verify_response['score'] < 0.5:
#             abort(401)

#         email = request.form.get('email')
#         first_name = request.form.get('firstName')
#         last_name = request.form.get('lastName')
#         user_name = request.form.get('userName')
#         password1 = request.form.get('password1')
#         password2 = request.form.get('password2')
#         role_id = request.form.get('role')

#         if User.query.filter_by(email=email).first():
#             flash('Email นี้มีผู้ใช้แล้ว', category='error')
#         elif User.query.filter_by(user_name=user_name).first():
#             flash('Username นี้มีผู้ใช้แล้ว', category='error')
#         elif len(email) < G_LEN_EMAIL or len(email) > NG_LEN_EMAIL:
#             flash('Email ต้องมีขนาดตั้งแต่ 4 - 50 ตัวอักษร', category='error')
#         elif len(user_name) < G_LEN_UNAME or len(user_name) > NG_LEN_UNAME:
#             flash('Username ต้องมีขนาดตั้งแต่ 4 - 50 ตัวอักษร', category='error')
#         elif len(first_name) < G_LEN_FNAME  or len(first_name) > NG_LEN_FNAME:
#             flash('ชื่อจริงต้องมีขนาดตั้งแต่ 2 - 50 ตัวอักษร', category='error')
#         elif len(last_name) < G_LEN_LNAME  or len(last_name) > NG_LEN_LNAME:
#             flash('นามสกุลต้องมีขนาดตั้งแต่ 2 - 50 ตัวอักษร', category='error')
#         elif password1 != password2:
#             flash('กรุณาใส่ Password ให้ตรงกัน', category='error')
#         elif len(password1) < G_LEN_PWORD or len(password1) > NG_LEN_PWORD:
#             flash('Password ต้องมีขนาดตั้งแต่ 7 - 50 ตัวอักษร', category='error')
#         else:
#             new_user = User(email=email, first_name=first_name, last_name=last_name, user_name=user_name, password=generate_password_hash(password1, method='pbkdf2:sha256'), role_id=role_id)
#             db.session.add(new_user)
#             db.session.commit()
#             login_user(new_user, remember=True)
#             flash('Account created!', category='success')

#             filename = None
#             if 'profile_picture' in request.files:
#                 profile_picture = request.files['profile_picture']
            
#                 if profile_picture and allowed_file(profile_picture.filename):
#                     filename = secure_filename(profile_picture.filename)
#                     filename = f"{new_user.user_id}_profile.jpg"

#                     file_path = os.path.join(PROFILE_FOLDER, filename)
#                     profile_picture.save(file_path)
            
#             new_user.profile_picture = filename
#             db.session.add(new_user)
#             db.session.commit()

#             return redirect(url_for('views_blueprint.home'))

#     return render_template("sign_up.html", user=current_user, roles=sorted_roles, site_key=create_app().config['RECAPTCHA_SITE_KEY'])



# @auth_blueprint.route('/login', methods=['GET', 'POST'])
# def login():

#     if request.method == 'POST':

#         print(request.form)

#         secret_response = request.form['g-recaptcha-response']

#         verify_response = requests.post(url=f"{create_app().config['VERIFY_URL']}?secret={create_app().config['RECAPTCHA_SECRET_KEY']}&response={secret_response}").json()


#         if verify_response['success'] == False or verify_response['score'] < 0.5:
#             abort(401)

#         email = request.form.get('email')
#         password = request.form.get('password')

#         user = User.query.filter_by(email=email).first()
#         if user:
#             if check_password_hash(user.password, password):
#                 flash('Logged in successfully!', category='success')
#                 login_user(user, remember=True)
#                 return redirect(url_for('views_blueprint.home'))
#             else:
#                 flash('Incorrect password, try again.', category='error')
#         else:
#             flash('Email does not exist.', category='error')

#     return render_template("login.html", user=current_user, site_key=create_app().config['RECAPTCHA_SITE_KEY'])

@auth_blueprint.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        print(request.form)

        secret_response = request.form['g-recaptcha-response']

        verify_response = requests.post(url=f"{create_app().config['VERIFY_URL']}?secret={create_app().config['RECAPTCHA_SECRET_KEY']}&response={secret_response}").json()

        if verify_response['success'] == False or verify_response['score'] < 0.5:
            abort(401)

        email = request.form.get('email')
        password = request.form.get('password')

        user = User.query.filter_by(email=email).first()
        if user:
            if check_password_hash(user.password, password):
                flash('Logged in successfully!', category='success')
                login_user(user, remember=True)
                return redirect(url_for('views_blueprint.home'))
            else:
                flash('Incorrect password, try again.', category='error')
                # คืนฟอร์มแบบมีข้อมูลผู้ใช้กรอกมาแล้ว
                return render_template("login.html", user=current_user, site_key=create_app().config['RECAPTCHA_SITE_KEY'], email=email)
        else:
            flash('Email does not exist.', category='error')
            # คืนฟอร์มแบบมีข้อมูลผู้ใช้กรอกมาแล้ว
            return render_template("login.html", user=current_user, site_key=create_app().config['RECAPTCHA_SITE_KEY'], email=email)

    return render_template("login.html", user=current_user, site_key=create_app().config['RECAPTCHA_SITE_KEY'])

@auth_blueprint.route('/sign-up', methods=['GET', 'POST'])
def sign_up():
    sorted_roles = sorted(Role.query.all(), key=lambda x: locale.strxfrm(x.role_name))

    if request.method == 'POST':
        print(request.form)

        secret_response = request.form['g-recaptcha-response']
        verify_response = requests.post(url=f"{create_app().config['VERIFY_URL']}?secret={create_app().config['RECAPTCHA_SECRET_KEY']}&response={secret_response}").json()

        if verify_response['success'] == False or verify_response['score'] < 0.5:
            abort(401)

        email = request.form.get('email')
        first_name = request.form.get('firstName')
        last_name = request.form.get('lastName')
        user_name = request.form.get('userName')
        password1 = request.form.get('password1')
        password2 = request.form.get('password2')
        role_id = request.form.get('role')

        if User.query.filter_by(email=email).first():
            flash('Email นี้มีผู้ใช้แล้ว', category='error')
        elif User.query.filter_by(user_name=user_name).first():
            flash('Username นี้มีผู้ใช้แล้ว', category='error')
        elif len(first_name) < G_LEN_FNAME  or len(first_name) > NG_LEN_FNAME:
            flash('ชื่อจริงต้องมีขนาดตั้งแต่ 2 - 50 ตัวอักษร', category='error')
        elif len(last_name) < G_LEN_LNAME  or len(last_name) > NG_LEN_LNAME:
            flash('นามสกุลต้องมีขนาดตั้งแต่ 2 - 50 ตัวอักษร', category='error')
        elif len(user_name) < G_LEN_UNAME or len(user_name) > NG_LEN_UNAME:
            flash('Username ต้องมีขนาดตั้งแต่ 4 - 50 ตัวอักษร', category='error')
        elif len(email) < G_LEN_EMAIL or len(email) > NG_LEN_EMAIL:
            flash('Email ต้องมีขนาดตั้งแต่ 4 - 50 ตัวอักษร', category='error')
        elif password1 != password2:
            flash('กรุณาใส่ Password ให้ตรงกัน', category='error')
        elif len(password1) < G_LEN_PWORD or len(password1) > NG_LEN_PWORD:
            flash('Password ต้องมีขนาดตั้งแต่ 7 - 50 ตัวอักษร', category='error')
        else:
            new_user = User(email=email, first_name=first_name, last_name=last_name, user_name=user_name, password=generate_password_hash(password1, method='pbkdf2:sha256'), role_id=role_id)
            db.session.add(new_user)
            db.session.commit()
            login_user(new_user, remember=True)
            flash('Account created!', category='success')

            filename = None
            if 'profile_picture' in request.files:
                profile_picture = request.files['profile_picture']
            
                if profile_picture and allowed_file(profile_picture.filename):
                    filename = secure_filename(profile_picture.filename)

website/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %}Home{% endblock %}</title>

    <link
      rel="stylesheet"
      href="{{url_for('static', filename = 'css/bootstrap.min.css')}}"
    />
    <link
      href="{{url_for('static', filename = 'css/tiny-slider.css')}}"
      rel="stylesheet"
    />
    <link
      href="{{url_for('static', filename = 'css/style.css')}}"
      rel="stylesheet"
    />
    <link
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css"
      rel="stylesheet"
    />
    <link rel="stylesheet" href="https://use.typekit.net/gpk8twv.css">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" rel="stylesheet">
    {% block morestyle %}
    <style>
      .carousel {
        margin-bottom: 4rem;
      }
      .carousel {
        position: relative;
      }
      *,
      ::after,
      ::before {
        box-sizing: border-box;
      }

      user agent stylesheet div {
        display: block;
        unicode-bidi: isolate;
      }
      
    </style>
    {% endblock %}
    <!-- <link rel="stylesheet" href="/static/css/bootstrap.min.css">
  <link rel="stylesheet" href="/static/css/tiny-slider.css">
  <link rel="stylesheet" href="/static/css/style.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css"> -->
  </head>
  <body>
    <!-- Start Header/Navigation -->
    <nav
      class="custom-navbar navbar navbar navbar-expand-md navbar-dark bg-dark"
      arial-label="Furni navigation bar"
    >
      <div class="container">
        <!-- <img src="website\static\images\logo.png" alt="LOGO"> -->
        <a href="/">
          <img src="{{ url_for('static', filename='images/logo.png') }}" alt="LOGO" style="height: 100px; width: 100px;">
        </a>
      
        <a class="navbar-brand" href="/">Wood Anatomy<span>.</span></a>

        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarsFurni"
          aria-controls="navbarsFurni"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>

        {% if user.is_authenticated and user.role.role_name != 'Admin' %}
        <div class="collapse navbar-collapse " id="navbarsFurni">
          <ul class="custom-navbar-nav navbar-nav ms-auto mb-2 mb-md-0">
            <li><a class="nav-link" id="home" href="/">Home</a></li>
            <li>
              <a class="nav-link" id="woods-info" href="/woods-info"
                >Woods Information</a
              >
            </li>
            <li>
              <a class="nav-link" id="wood-identification" href="/wood-identification"
                >Identification</a
              >
            </li>
            <li>
              <a class="nav-link" id="predict" href="/prediction-history"
                >Identification History</a
              >
            </li>
            <li>
              <a class="nav-link" id="about" href="/about"
                >About Us</a
              >
            </li>
          </ul>
          <!-- photo คน -->
          <ul class="custom-navbar-cta navbar-nav mb-2 mb-md-0 ms-5">
            <li>
              <a class="nav-link" href="/profile">
                <img
                  src="{{ url_for('static', filename='images/user.svg') }}"
                />
              </a>
            </li>
            <li><a class="btn btn-dark" href="/logout">Logout</a></li>
          </ul>
          {% elif user.is_authenticated and user.role.role_name == 'Admin' %}
          <ul class="custom-navbar-cta navbar-nav mb-2 mb-md-0 ms-5">
            <li>
              <a class="nav-link" id="admin-manage" href="/manage"
                >Admin Manage</a
              >
            </li>
            <li><a class="btn btn-dark" href="/logout">Logout</a></li>
          </ul>
          {% else %}
          <div class="collapse navbar-collapse" id="navbarsFurni">
            <ul class="custom-navbar-nav navbar-nav ms-auto mb-2 mb-md-0">
              <li><a class="nav-link" id="home" href="/">Home</a></li>
              <li>
                <a class="nav-link" id="woods-info" href="/woods-info"
                  >Woods Information</a
                >
              </li>
              <li>
                <a class="nav-link" id="predict" href="/wood-identification"
                  >Identification</a
                >
              </li>
              <li>
                <a class="nav-link" id="about" href="/about"
                  >About Us</a
                >
              </li>
            </ul>
            <ul class="custom-navbar-cta navbar-nav mb-2 mb-md-0 ms-5">
              <li>
                <a class="btn btn-outline-dark" href="/login">Login</a>
              </li>
              <a href="/sign-up" class="btn btn-dark" role="button"
                >Create Account</a
              >
            </ul>
          </div>
          {% endif %}
        </div>
      </div>
    </nav>
    <!-- End Header/Navigation -->




    
    {% block content %} {% endblock %}

    <!-- Start Footer Section -->
    <footer class="footer-section text-center ">
      <div class="container relative">
        <div class="row g-5 mb-5 justify-content-center">
          <div class="col-lg-4 justify-content-center">
            <div class="mb-4 footer-logo-wrap text-center justify-content-center">
              <a href="/">
                <img src="/static/images/logo.png" alt="LOGO" style="height: 100px; width: 100px; display: block; margin: 0 auto;">
              </a>
              <br>
              <a href="/" class="footer-logo">Wood Anatomy<span>.</span></a>
            </div>
          </div>
    
          <div class="col-lg-4">
            <h5>Address</h5>
            <p class="mb-4">
              50 ถนน งามวงศ์วาน แขวงลาดยาว เขตจตุจักร กรุงเทพมหานคร 10900
              <br />มหาวิทยาลัยเกษตรศาสตร์
            </p>
    
            
          </div>
    
          <div class="col-lg-4">
            <h5>Contact</h5>
            <p class="mb-4">0-2579-0113, <br />0-2942-8200-45</p>
            <ul class="list-unstyled custom-social">
              <li>
                <a href="https://www.facebook.com/comsci.ku"><span class="fab fa-facebook-f"></span></a>
              </li>
              <li>
                <a href="https://www.instagram.com/comsci.ku/"><span class="fab fa-instagram"></span></a>
              </li>
            </ul>
          </div>
        </div>
    
        <div class="border-top copyright">
          <div class="row justify-content-center">
            <!-- <div class="col-lg-6"> -->
              <p >
                Copyright &copy;
                <script>
                  document.write(new Date().getFullYear());
                </script>
                . All Rights Reserved.
                <!-- License information: https://untree.co/license/ -->
              </p>
            </div>
          </div>
        </div>
      </div>
    </footer>
    
    <style>
      .copyright {
        text-align: center;
        margin-top: 20px;
        margin-bottom: 20px;
      }
    </style>
    
    <!-- End Footer Section -->
    <script src="static\js\bootstrap.min.js"></script>
    <!-- <script src="static\js\tiny-slider.js"></script>
    <script src="static\js\custom.js"></script> -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"></script>
    <!-- <script src="https://stackpath.bootstrapcdn.com/bootstrap/5.1.3/js/bootstrap.min.js"></script> -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>

    <script>
      $(document).ready(function() {
          {% with messages = get_flashed_messages(with_categories=true) %}
              {% if messages %}
                  {% for category, message in messages %}
                      {% if category == 'error' %}
                          toastr.error('{{ message }}');
                      {% else %}
                          toastr.success('{{ message }}');
                      {% endif %}
                  {% endfor %}
              {% endif %}
          {% endwith %}
      });
  </script>
  </body>
</html>

website/templates/login.html
{% extends "base.html" %} 
{% block title %}Login{% endblock %} 

{% block morestyle %}
<style>
  .card {
    border: none;
    border-radius: 15px;
    box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
  }
  .form-container {
    background-color: #fff;
    border-radius: 30px;
    padding: 10px 35px; /* รวมการใส่ padding ให้สั้นลง */
    box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
  }
</style>
{% endblock %} 

{% block content %}
<script src="https://www.google.com/recaptcha/api.js"></script>

<script>
  function onSubmit(token) {
    document.getElementById("log-in-form").submit();
  }
</script>

<form id="log-in-form" action="{{ url_for('auth_blueprint.login') }}" method="POST" novalidate>
  <section class="vh-75">
    <div class="container h-100">
      <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col">
          <div class="row g-0">
            <div class="col-xl-5 d-none d-xl-block mt-4">
              <img src="{{url_for('static', filename='images/signin-image1.png')}}" class="img-fluid" alt="Sample image" />
            </div>
            <div class="col-xl-7">
              <div class="form-container">
                <p class="text-center h1 fw-bold mb-5 mx-1 mx-md-4 mt-4">Login</p>
                <form method="POST" class="mx-1 mx-md-4">
                  <div class="d-flex flex-row align-items-center mb-2">
                    <div data-mdb-input-init class="form-outline flex-fill mb-0">
                      <input type="email" class="form-control" id="email" name="email" placeholder="Enter email" value="{{ email }}" /> <!-- แสดงค่า email ที่ส่งกลับมา -->
                      <label class="form-label" for="email">Your Email</label>
                    </div>
                  </div>

                  <div class="d-flex flex-row align-items-center mb-2">
                    <div data-mdb-input-init class="form-outline flex-fill mb-0">
                      <input type="password" class="form-control" id="password" name="password" placeholder="Enter password" />
                      <label class="form-label" for="password">Password</label>
                    </div>
                  </div>

                  <div class="d-flex justify-content-center flex-column align-items-center mx-4 mb-3 mb-lg-4">
                    <button type="submit" data-mdb-button-init data-mdb-ripple-init class="g-recaptcha btn btn-primary mb-2" data-sitekey={{ site_key }} data-callback='onSubmit' data-action='submit'>Login</button>
                    <a href="/sign-up" class="btn btn-link">Create an account</a>
                  </div>
                  <br />
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
</form>
{% endblock %}

website/templates/sign_up.html
{% extends "base.html" %}
{% block title %}Sign Up{% endblock %}
{% block morestyle %}
<style>
  /* body {
      background-color: #f8f9fa;
  } */
  .image-preview {
    object-fit: cover;
    display: flex;
    flex-direction: column;
    justify-content: center;
    align-items: center;
    text-align: center;
    border-radius: 50%;
    width: 400px;
    /* ปรับขนาดรูปโปรไฟล์ตามต้องการ */
    height: 400px;
    /* ปรับขนาดรูปโปรไฟล์ตามต้องการ */
    object-fit: cover;
    /* ความสัมพันธ์ของรูปภาพกับองค์ประกอบ */
  }

  .card {
    border: none;
    /* border-radius: 15px; */
    /* box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1); */
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    text-align: center;
  }

  .btn-upload {
    background-color: #007bff;
    color: white;
    border-radius: 50px;
  }

  .btn-upload:hover {
    background-color: #0056b3;
  }

  .file-name {
    text-align: center;
    margin-top: 10px;
    font-style: italic;
    color: #6c757d;
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    text-align: center;
  }

  input[type="file"] {
    display: none;
  }

  .form-container {
    background-color: #fff; /* พื้นหลังสีขาว */
    border-radius: 30px; /* ขอบมุมมน */
    /* padding: -10px;ระยะห่างภายใน */
    box-shadow: 0 0 10px rgba(0, 0, 0, 0.1); /* เพิ่มเงา */
  }
  
</style>
{% endblock %}

{% block content %}
<script src="https://www.google.com/recaptcha/api.js"></script>

<script>
  function onSubmit(token) {
    document.getElementById("sign-up-form").submit();
  }
</script>

<form id="sign-up-form" action="{{ url_for('auth_blueprint.sign_up') }}" method="POST" enctype="multipart/form-data">
  <div class="container h-100">
    <div class="row d-flex justify-content-center align-items-center ">
      <div class="form-container">
        <div class="row g-0">
          <div class="col-xl-6 justify-content-center align-items-center text-center" style="margin-top: 50px;">
            <div class="card mt-md-4 p-4">
              <div class="mb-3">
                <div id="imagePreview" class="mt-4 text-center">
                  <img id="previewImg" class="img-fluid image-preview" src="{{ url_for('static', filename='images/default_profile.jpg') }}" alt="Your image will appear here" style="justify-content: center; align-items: center; text-align: center">
                  <div id="fileName" class="file-name"></div>
                </div>
              </div>
              <input class="form-control" type="file" id="profile_picture" accept="image/*" name="profile_picture">
              <button type="button" class="btn btn-upload mt-2"><i class="fa-solid fa-upload"></i> Choose profile picture</button>
            </div>
          </div>
          <div class="col-xl-6">
            <div class="card-body p-md-5 text-black">
              <p class="text-center h1 fw-bold mb-5 mx-1 mx-md-4 mt-4">
                Create Account
              </p>
              <div class="d-flex flex-row align-items-center mb-2">
                <div data-mdb-input-init class="form-outline flex-fill mb-0">
                  <input type="text" class="form-control" id="firstName" name="firstName" placeholder="ชื่อจริงต้องมีขนาดตั้งแต่ 2 - 50 ตัวอักษร" value="{{ request.form.firstName }}" />
                  <label class="form-label" for="form3Example1c">First Name</label>
                </div>
              </div>
              <div class="d-flex flex-row align-items-center mb-2">
                <div data-mdb-input-init class="form-outline flex-fill mb-0">
                  <input type="text" class="form-control" id="lastName" name="lastName" placeholder="นามสกุลต้องมีขนาดตั้งแต่ 2 - 50 ตัวอักษร" value="{{ request.form.lastName }}" />
                  <label class="form-label" for="form3Example1c">Last Name</label>
                </div>
              </div>
              <div class="d-flex flex-row align-items-center mb-2">
                <div data-mdb-input-init class="form-outline flex-fill mb-0">
                  <input type="text" class="form-control" id="userName" name="userName" placeholder="ชื่อผู้ใช้ต้องมีขนาดตั้งแต่ 4 - 50 ตัวอักษร" value="{{ request.form.userName }}" />
                  <label class="form-label" for="form3Example1c">User Name</label>
                </div>
              </div>
              <div class="d-flex flex-row align-items-center mb-2">
                <div data-mdb-input-init class="form-outline flex-fill mb-0">
                  <input type="email" class="form-control" id="email" name="email" placeholder="Email ต้องมีขนาดตั้งแต่ 2 - 50 ตัวอักษร" value="{{ request.form.email }}" />
                  <label class="form-label" for="form3Example3c">Email</label>
                </div>
              </div>
              <div class="d-flex flex-row align-items-center mb-2">
                <div data-mdb-input-init class="form-outline flex-fill mb-0">
                  <input type="password" class="form-control" id="password1" name="password1" placeholder="Password ต้องมีขนาดตั้งแต่ 7 - 50 ตัวอักษร" value="{{ request.form.password1 }}" />
                  <label class="form-label" for="form3Example4c">Password</label>
                </div>
              </div>
              <div class="d-flex flex-row align-items-center mb-2">
                <div data-mdb-input-init class="form-outline flex-fill mb-0">
                  <input type="password" class="form-control" id="password2" name="password2" placeholder="Password ต้องมีขนาดตั้งแต่ 7 - 50 ตัวอักษร" value="{{ request.form.password2 }}" />
                  <label class="form-label" for="form3Example4cd">Confirm password</label>
                </div>
              </div>
              <div class="d-flex flex-row align-items-center mb-2">
                <div data-mdb-input-init class="form-outline flex-fill mb-0">
                  <select class="form-select" id="role" name="role" required>
                    {% for role in roles %}
                    <option value="{{ role.role_id }}" {% if role.role_id == request.form.role %}selected{% endif %}>
                      {{ role.role_name }}
                    </option>
                    {% endfor %}
                  </select>
                  <label class="form-label select-label">Role</label>
                </div>
              </div>
              <div class="d-flex justify-content-center flex-column align-items-center mx-4 mb-3 mb-lg-4">
                <button type="submit" data-mdb-button-init data-mdb-ripple-init class="g-recaptcha btn btn-primary mb-2" data-sitekey="{{site_key}}" data-callback="onSubmit" data-action="submit">Create Account</button>
                <a href="/login" class="btn btn-link">I am already member</a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</form>
<script>
  document.querySelector('.btn-upload').addEventListener('click', function () {
    document.getElementById('profile_picture').click();
  });

  document.getElementById('profile_picture').addEventListener('change', function (event) {
    const file = event.target.files[0];
    if (file) {
      const reader = new FileReader();
      reader.onload = function (e) {
        const previewImg = document.getElementById('previewImg');
        const fileName = document.getElementById('fileName');
        previewImg.src = e.target.result;
        previewImg.style.display = 'block';
        fileName.textContent = file.name;
      };
      reader.readAsDataURL(file);
    }
  });
</script>


{% endblock %}